title: <center>Alexia Wells</center> # your name (or website title) here
logo: "RetryHeadshot.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)

 <br>
 <center>
 <a href="Alexia_Wells.2024.pdf">Resume</a> |
 <a href="https://www.linkedin.com/in/alexia-wells/">LinkedIn</a> |
 <a href="https://github.com/alexiacw11">GitHub</a> <br><br>
 </center>

  Welcome to my page! I am pursuing a Master's in Business Analytics at the David Eccles School of Business, University of Utah.
  
  <br><br>
  I also work as a course coordinator in the Statistics department at Brigham Young University. 
  <br><br>
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
