title: <center>Alexia Wells</center> 
logo: "RetryHeadshot.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)

 <br>
 <center>
 <a href="Alexia_Wells.2024.pdf">Resume</a> |
 <a href="https://www.linkedin.com/in/alexia-wells/">LinkedIn</a> <br>
 <a href="https://alexiacw11.wixsite.com/spanish-portfolio">Spanish Proficiency</a> |
 <a href="https://github.com/alexiacw11">GitHub</a> <br><br>
 </center>

  Welcome to my page! I graduated with a Master of Science in Business Analytics from the David Eccles School of Business, University of Utah. I received bachelor's degrees from Brigham Young University in Statistics: Data Science and Spanish Studies. 
  
  <br><br>
I am a course coordinator in the Statistics Department at BYU and am interested in analytical roles in Austin, TX. 
  <br><br>
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
